
# Set the environment variables
- name: Configure environment variables
  script: environment_setup.sh

# Get the debian file into tmp/ folder
- name: Download node v6 
  get_url:
    url: https://deb.nodesource.com/setup_6.x
    dest: /tmp/setup.sh
    mode: 0777

# Run the script file
- name: Install node v6  
  command: /bin/sh /tmp/setup.sh
  become: yes

# Run the nodejs installation
- name: Remove old node js
  shell: 'apt-get -y install nodejs'
  become: yes

# Install forever
- name: Installing forever js
  shell: npm install -g forever
  become: yes

# Install Git
- name: Installing git
  apt:
    name: git
    state: latest
    update_cache: true
  become: yes

# Clone the git repository
- name: Cloning Git Repo
  git: repo=https://{{ git_username }}:{{ git_password }}@github.ncsu.edu/ssrivas8/CSC510Project.git dest=/home/ubuntu/Project version=sindhu

# Run npm install into bot/ folder
- name: Running NPM install
  shell: npm install
  args:
    chdir: /home/ubuntu/Project/bot
  become: yes

# Run the forever on 4390 port
- name: Start the forever server 4390
  shell: "forever start bot.js 4390"
  args:
    chdir: /home/ubuntu/Project/bot
  become: yes
    
# Delete the tmp/ folder 
- name: Deleting files from temp directory
  file: path=/tmp/* state=absent
  become: yes