- name: Install npm
  apt:
    name: npm
    state: latest
    update_cache: yes
  become: yes

- name: Install node.js
  apt:
    name: nodejs-legacy
    state: latest
    update_cache: yes
    install_recommends: no
  become: yes

- name: Installing forever js
  shell: npm install -g forever
  become: yes

- name: Installing git
  apt:
    name: git
    state: latest
    update_cache: true
  become: yes

    # - name: Create the Github SSH public key file
    #   copy: src="/home/vagrant_data/deployment/github_rsa.pub"
    #         dest="/home/ubuntu/.ssh/id_rsa.pub"
    #         mode=0644
    #         owner=ubuntu
    #         group=ubuntu

    # - name: Create the Github SSH private key file
    #   copy: src="/home/vagrant_data/deployment/github_rsa"
    #         dest="/home/ubuntu/.ssh/id_rsa"
    #         mode=0600
    #         owner=ubuntu
    #         group=ubuntu

    # - name: Setup the Git repo
    #   become: no
    #   git:  repo=https://github.ncsu.edu/ssrivas8/CSC510Project.git
    #         version=master
    #         dest=/home/ubuntu/Project
    #         accept_hostkey=yes
    #         key_file="/home/ubuntu/.ssh/id_rsa"

- name: Cloning Git Repo
  git: repo=https://{{ git_username }}:{{ git_password }}@github.ncsu.edu/ssrivas8/CSC510Project.git dest=/home/ubuntu/Project version=milestone3


- name: Running NPM install
  shell: npm install
  args:
    chdir: /home/ubuntu/Project/bot
  become: yes
    
- name: Configure environment variables
  script: environment_setup.sh

- name: Start the forever server
  shell: "forever start bot.js"
  args:
    chdir: /home/ubuntu/Project/bot
  become: yes
    
- name: Deleting files from temp directory
  file: path=/tmp/* state=absent
  become: yes